/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2025 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-x86_64"
#define DATE "built on: Tue Mar  4 12:16:49 2025 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','/','h','o','m','e','/',
    't','o','n','y','/','.','a','p','p','l','i','c','a','t','i','o',
    'n','/','M','i','n','i','c','o','n','d','a','/','e','n','v','s',
    '/','m','y','p','y','t','o','r','c','h','/','b','i','n','/','x',
    '8','6','_','6','4','-','c','o','n','d','a','-','l','i','n','u',
    'x','-','g','n','u','-','c','c',' ','-','f','P','I','C',' ','-',
    'p','t','h','r','e','a','d',' ','-','m','6','4',' ','-','W','a',
    ',','-','-','n','o','e','x','e','c','s','t','a','c','k',' ','-',
    'm','a','r','c','h','=','n','o','c','o','n','a',' ','-','m','t',
    'u','n','e','=','h','a','s','w','e','l','l',' ','-','f','t','r',
    'e','e','-','v','e','c','t','o','r','i','z','e',' ','-','f','P',
    'I','C',' ','-','f','s','t','a','c','k','-','p','r','o','t','e',
    'c','t','o','r','-','s','t','r','o','n','g',' ','-','f','n','o',
    '-','p','l','t',' ','-','O','2',' ','-','f','f','u','n','c','t',
    'i','o','n','-','s','e','c','t','i','o','n','s',' ','-','p','i',
    'p','e',' ','-','i','s','y','s','t','e','m',' ','/','h','o','m',
    'e','/','t','o','n','y','/','.','a','p','p','l','i','c','a','t',
    'i','o','n','/','M','i','n','i','c','o','n','d','a','/','e','n',
    'v','s','/','m','y','p','y','t','o','r','c','h','/','i','n','c',
    'l','u','d','e',' ','-','m','a','r','c','h','=','n','o','c','o',
    'n','a',' ','-','m','t','u','n','e','=','h','a','s','w','e','l',
    'l',' ','-','f','t','r','e','e','-','v','e','c','t','o','r','i',
    'z','e',' ','-','f','P','I','C',' ','-','f','s','t','a','c','k',
    '-','p','r','o','t','e','c','t','o','r','-','s','t','r','o','n',
    'g',' ','-','f','n','o','-','p','l','t',' ','-','O','2',' ','-',
    'f','f','u','n','c','t','i','o','n','-','s','e','c','t','i','o',
    'n','s',' ','-','p','i','p','e',' ','-','i','s','y','s','t','e',
    'm',' ','/','h','o','m','e','/','t','o','n','y','/','.','a','p',
    'p','l','i','c','a','t','i','o','n','/','M','i','n','i','c','o',
    'n','d','a','/','e','n','v','s','/','m','y','p','y','t','o','r',
    'c','h','/','i','n','c','l','u','d','e',' ','-','D','O','P','E',
    'N','S','S','L','_','U','S','E','_','N','O','D','E','L','E','T',
    'E',' ','-','D','L','_','E','N','D','I','A','N',' ','-','D','O',
    'P','E','N','S','S','L','_','P','I','C',' ','-','D','O','P','E',
    'N','S','S','L','_','B','U','I','L','D','I','N','G','_','O','P',
    'E','N','S','S','L',' ','-','D','N','D','E','B','U','G',' ','-',
    'D','N','D','E','B','U','G',' ','-','D','_','F','O','R','T','I',
    'F','Y','_','S','O','U','R','C','E','=','2',' ','-','O','2',' ',
    '-','i','s','y','s','t','e','m',' ','/','h','o','m','e','/','t',
    'o','n','y','/','.','a','p','p','l','i','c','a','t','i','o','n',
    '/','M','i','n','i','c','o','n','d','a','/','e','n','v','s','/',
    'm','y','p','y','t','o','r','c','h','/','i','n','c','l','u','d',
    'e',' ','-','D','N','D','E','B','U','G',' ','-','D','_','F','O',
    'R','T','I','F','Y','_','S','O','U','R','C','E','=','2',' ','-',
    'O','2',' ','-','i','s','y','s','t','e','m',' ','/','h','o','m',
    'e','/','t','o','n','y','/','.','a','p','p','l','i','c','a','t',
    'i','o','n','/','M','i','n','i','c','o','n','d','a','/','e','n',
    'v','s','/','m','y','p','y','t','o','r','c','h','/','i','n','c',
    'l','u','d','e','\0'
};
